//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace efcv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Valuesi
    {
        public long ValueiID { get; set; }
        public Nullable<int> SensoriID { get; set; }
        public string Value { get; set; }
        public string TimeStamp { get; set; }
    
        public virtual Sensori Sensori { get; set; }
    }
}
